/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AdminLazyImport = createFileRoute('/admin')()
const IndexLazyImport = createFileRoute('/')()
const EventoEventoLazyImport = createFileRoute('/evento/$evento')()
const AdminLoginLazyImport = createFileRoute('/admin/login')()
const IscrizioneEventoTokenLazyImport = createFileRoute(
  '/iscrizione/$evento/$token',
)()

// Create/Update Routes

const AdminLazyRoute = AdminLazyImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const EventoEventoLazyRoute = EventoEventoLazyImport.update({
  path: '/evento/$evento',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/evento.$evento.lazy').then((d) => d.Route),
)

const AdminLoginLazyRoute = AdminLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.login.lazy').then((d) => d.Route))

const IscrizioneEventoTokenLazyRoute = IscrizioneEventoTokenLazyImport.update({
  path: '/iscrizione/$evento/$token',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/iscrizione.$evento.$token.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginLazyImport
      parentRoute: typeof AdminLazyImport
    }
    '/evento/$evento': {
      id: '/evento/$evento'
      path: '/evento/$evento'
      fullPath: '/evento/$evento'
      preLoaderRoute: typeof EventoEventoLazyImport
      parentRoute: typeof rootRoute
    }
    '/iscrizione/$evento/$token': {
      id: '/iscrizione/$evento/$token'
      path: '/iscrizione/$evento/$token'
      fullPath: '/iscrizione/$evento/$token'
      preLoaderRoute: typeof IscrizioneEventoTokenLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AdminLazyRoute: AdminLazyRoute.addChildren({ AdminLoginLazyRoute }),
  EventoEventoLazyRoute,
  IscrizioneEventoTokenLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/evento/$evento",
        "/iscrizione/$evento/$token"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/admin": {
      "filePath": "admin.lazy.tsx",
      "children": [
        "/admin/login"
      ]
    },
    "/admin/login": {
      "filePath": "admin.login.lazy.tsx",
      "parent": "/admin"
    },
    "/evento/$evento": {
      "filePath": "evento.$evento.lazy.tsx"
    },
    "/iscrizione/$evento/$token": {
      "filePath": "iscrizione.$evento.$token.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
