services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: elestio/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: asdasd123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json:ro

volumes:
  postgres_data:
    name: postgres_data
    driver: local
